language: ruby
rvm:
 - 2.1.1
before_script:
  - psql -c 'create database binofparts_test;' -U postgres
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate --trace
script: 
  - RAILS_ENV=test bundle exec rake spec