language: ruby
rvm:
 - 2.1.1
env:
  global:
    - RAILS_ENV=test
before_script:
  - psql -c 'create database binofparts_test;' -U postgres
  - bundle exec rake db:migrate
script: bundle exec rake spec