language: ruby
rvm:
 - 2.1.1
env:
  - RAILS_ENV=test
  - DB=postgresql
before_script:
  - psql -c 'create database binofparts_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate
script: 
  -bundle exec rake spec