language: ruby
rvm:
 - 2.1.1
env: 
  - RAILS_ENV=test
before_script:
  - psql -c 'create database binofparts_test;' -U postgres
  - cp config/database-travis.yml config/database.yml
  - bundle exec rake db:create db:migrate
script: rspec spec